#!/usr/bin/env php
<?php

require_once __DIR__."/../vendor/autoload.php";

use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;
use Source\Util\EntityManagerFactory;

ConsoleRunner::run(
    new SingleManagerProvider(EntityManagerFactory::getEntityManager())
);
